# First is to import numpy library

In [6]:
import numpy as np

* Defining new array

In [8]:
myarr = np.array([12,12,33,22,566])
myarr

array([ 12,  12,  33,  22, 566])

In [10]:
list=['hello',"hi",22,33,4.4]
arr= np.array(list)
arr

array(['hello', 'hi', '22', '33', '4.4'], dtype='<U32')

In [12]:
arr=np.array(["Hello", 'hi'])
arr

array(['Hello', 'hi'], dtype='<U5')

In [13]:
arr=np.array([22,34,65,2.4,44])
arr

array([22. , 34. , 65. ,  2.4, 44. ])

* Generating Array

1. Generating sequence

In [17]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [16]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

2. Generating array of zeros

In [20]:
arr= np.zeros(6) #vector
arr

array([0., 0., 0., 0., 0., 0.])

In [19]:
arr= np.zeros((6,7)) #matrix
arr

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [21]:
arr= np.zeros((3,2,5)) #Tensor
arr

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [24]:
arr= np.zeros((2,3,2,3))
arr

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

3. Generating array of ones

In [25]:
arr= np.ones(32)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
arr= np.ones((5,7))
arr

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

* Extracting x numbers from range a to b

In [28]:
arr= np.linspace(1,10,3)
arr

array([ 1. ,  5.5, 10. ])

In [30]:
arr= np.linspace(20,100,7)
arr

array([ 20.        ,  33.33333333,  46.66666667,  60.        ,
        73.33333333,  86.66666667, 100.        ])

* We can get random values from 0 to one called as Normalization

In [31]:
np.random.rand(5)

array([0.67569322, 0.28997392, 0.64345217, 0.97429945, 0.68094624])

* If you want values from -3 to 3 called as Standerdization

In [38]:
np.random.randn(7)

array([ 0.1187914 , -0.19708307,  0.7721413 ,  2.43462566, -0.5818792 ,
        0.77046601, -1.4327336 ])

In [33]:
np.random.randn(7)

array([-0.14396825,  0.92663336,  0.40553432,  0.70952512, -0.80040221,
       -0.20284607,  1.06754709])

* To get random elements from specific range

In [39]:
np.random.randint(10,20,30) #(from, to, frequency)

array([12, 13, 12, 11, 13, 17, 19, 16, 19, 10, 16, 14, 14, 13, 17, 10, 10,
       19, 18, 16, 19, 19, 10, 14, 15, 11, 19, 18, 16, 13], dtype=int32)

# Array Attributes

In [42]:
arr= np.array([[np.random.randint(10,20,30)] for _ in range(3)])
arr

array([[[13, 17, 19, 11, 17, 16, 17, 10, 12, 10, 12, 11, 11, 14, 15, 10,
         12, 16, 19, 15, 13, 14, 16, 10, 16, 11, 11, 16, 16, 15]],

       [[16, 18, 10, 17, 16, 13, 19, 12, 14, 16, 12, 11, 17, 15, 14, 12,
         13, 15, 19, 17, 16, 14, 13, 17, 11, 14, 15, 10, 17, 10]],

       [[12, 14, 12, 14, 19, 11, 11, 18, 17, 13, 15, 18, 17, 18, 17, 15,
         10, 18, 18, 14, 15, 12, 17, 17, 15, 14, 15, 15, 14, 15]]],
      dtype=int32)

In [44]:
arr.shape

(3, 1, 30)

In [45]:
arr.size

90

In [46]:
arr.dtype

dtype('int32')

# Array Methodes

In [47]:
arr.min()

np.int32(10)

In [48]:
arr.max()

np.int32(19)

In [49]:
arr.sum()

np.int64(1298)

In [52]:
np.sum(arr,axis=0)

array([[41, 49, 41, 42, 52, 40, 47, 40, 43, 39, 39, 40, 45, 47, 46, 37,
        35, 49, 56, 46, 44, 40, 46, 44, 42, 39, 41, 41, 47, 40]])

In [53]:
np.sum(arr,axis=1)

array([[13, 17, 19, 11, 17, 16, 17, 10, 12, 10, 12, 11, 11, 14, 15, 10,
        12, 16, 19, 15, 13, 14, 16, 10, 16, 11, 11, 16, 16, 15],
       [16, 18, 10, 17, 16, 13, 19, 12, 14, 16, 12, 11, 17, 15, 14, 12,
        13, 15, 19, 17, 16, 14, 13, 17, 11, 14, 15, 10, 17, 10],
       [12, 14, 12, 14, 19, 11, 11, 18, 17, 13, 15, 18, 17, 18, 17, 15,
        10, 18, 18, 14, 15, 12, 17, 17, 15, 14, 15, 15, 14, 15]])

In [54]:
arr.mean()

np.float64(14.422222222222222)

In [55]:
arr.std()

np.float64(2.6372451020705414)

In [56]:
arr.argmax()

np.int64(2)

In [57]:
arr.argmin()

np.int64(7)

# Recizing and Reshaping

In [60]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [59]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

# Indexing and Slicing

* Vectors

In [61]:
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [62]:
arr[9]

np.int64(10)

In [63]:
arr[3:10]

array([ 4,  5,  6,  7,  8,  9, 10])

In [64]:
arr[:5]

array([1, 2, 3, 4, 5])

In [65]:
arr[9:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [66]:
arr[3::2]

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20])

* Matrix

In [68]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [72]:
arr[5] #rows

array([26, 27, 28, 29, 30])

In [71]:
arr[3,1] #[row,col]

np.int64(17)

* Slicing a specific portion from matrix:

In [80]:
arr[0:4,1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [82]:
arr[2:,3:]

array([[14, 15],
       [19, 20],
       [24, 25],
       [29, 30]])

In [83]:
arr[:2,:3]

array([[1, 2, 3],
       [6, 7, 8]])

* To get specific row

In [85]:
arr[2]

array([11, 12, 13, 14, 15])

In [87]:
arr[2,:] #or

array([11, 12, 13, 14, 15])

* To get specific column

In [88]:
arr[:,4]

array([ 5, 10, 15, 20, 25, 30])

# Boolean Indexing

In [90]:
arr= np.arange(11,22)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [92]:
bool_idx = arr%2==0
bool_idx

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [95]:
arr = arr[arr%2==0]
arr

array([12, 14, 16, 18, 20])