In [4]:
import numpy as np

# Arithematic Operations

In [9]:
a = np.arange(1,11)
b = np.arange(11,21)
a,b

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]))

In [10]:
a+b

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [11]:
a-b

array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [12]:
a*b

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171, 200])

In [13]:
a/b

array([0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333,
       0.375     , 0.41176471, 0.44444444, 0.47368421, 0.5       ])

In [14]:
a//b

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
a%b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
a**b

array([                  1,                4096,             1594323,
                 268435456,         30517578125,       2821109907456,
           232630513987207,   18014398509481984, 1350851717672992089,
       7766279631452241920])

# Broadcasting

In [19]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
a+10

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [22]:
a-10

array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0])

In [23]:
a*10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [24]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [25]:
a//2

array([0, 1, 1, 2, 2, 3, 3, 4, 4, 5])

In [26]:
a%2

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [27]:
a**3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [29]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [30]:
arr+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

# Shallow Copy VS deep Copy

- Shallow Copy

In [32]:
a = np.arange(26)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [33]:
b=a[5:] #shallow copy means if b changes, it won't reflect in a
b

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25])

In [34]:
b[4]=333
b,a

(array([  5,   6,   7,   8, 333,  10,  11,  12,  13,  14,  15,  16,  17,
         18,  19,  20,  21,  22,  23,  24,  25]),
 array([  0,   1,   2,   3,   4,   5,   6,   7,   8, 333,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25]))

- Deep Copy

In [35]:
a = np.arange(26)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [36]:
b = a #Deep copy means if b changes it will reflect in a

In [37]:
b[2]=1111111
a,b

(array([      0,       1, 1111111,       3,       4,       5,       6,
              7,       8,       9,      10,      11,      12,      13,
             14,      15,      16,      17,      18,      19,      20,
             21,      22,      23,      24,      25]),
 array([      0,       1, 1111111,       3,       4,       5,       6,
              7,       8,       9,      10,      11,      12,      13,
             14,      15,      16,      17,      18,      19,      20,
             21,      22,      23,      24,      25]))

# Dot Product

In [38]:
# There are two methods of generating dot product

In [47]:
a= np.array([[2,3,4],[2,3,7]])
b= np.array([[33,44],[22,22],[34,22]])
a,b

(array([[2, 3, 4],
        [2, 3, 7]]),
 array([[33, 44],
        [22, 22],
        [34, 22]]))

In [44]:
# Method 1

In [48]:
a @ b

array([[268, 242],
       [370, 308]])

In [49]:
# Method 2

In [50]:
np.dot(a,b)

array([[268, 242],
       [370, 308]])

# Transpose

In [51]:
arr= np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [52]:
arr.T #Transpose

array([[1, 3],
       [2, 4]])

# Stacking of arrays

In [53]:
a = np.array([22,33,44,55])
b = np.array([66,77,88,99])
a,b

(array([22, 33, 44, 55]), array([66, 77, 88, 99]))

In [54]:
#Vertical stactking

In [57]:
np.vstack((a,b))

array([[22, 33, 44, 55],
       [66, 77, 88, 99]])

In [58]:
#Horizontal Stacking

In [59]:
np.hstack((a,b))

array([22, 33, 44, 55, 66, 77, 88, 99])

In [60]:
#Column Stacking

In [61]:
np.column_stack((a,b))

array([[22, 66],
       [33, 77],
       [44, 88],
       [55, 99]])

# Spliting of Arrays

In [62]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# hsplit

In [63]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [64]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [65]:
# Vsplit

In [66]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [67]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]