In [1]:
import numpy as np

# Columns: [Employee Age, Hours Worked (per week), Performance Score (out of 100)]
# Rows: 6 different employees
startup_data = np.array([
    [24, 45, 88],   # Employee 1
    [30, 40, 92],   # Employee 2
    [22, 50, 75],   # Employee 3
    [35, 38, 95],   # Employee 4
    [28, 42, 85],   # Employee 5
    [40, 60, 98]    # Employee 6
])

In [2]:
# 1. Get the shape of the matrix to confirm how many employees and features you have.
startup_data.shape

(6, 3)

In [3]:
# 2. Extract ONLY the 'Performance Score' of all employees.
startup_data[:,2]

array([88, 92, 75, 95, 85, 98])

In [4]:
# 3. Find the average 'Hours Worked' across the entire team.
np.average(startup_data[:,1])

np.float64(45.833333333333336)

In [5]:
# 4. Find the maximum 'Performance Score' achieved in the company.
np.max(startup_data[:,2])

np.int64(98)

In [8]:
# 5. Get the details of the employees who are older than 25.
startup_data[startup_data[:,0]>25]

array([[30, 40, 92],
       [35, 38, 95],
       [28, 42, 85],
       [40, 60, 98]])

In [9]:
# 6. Find the ages of employees who scored exactly or below 85 in performance.
# (Hint: Select the row condition, then isolate the age column!)
startup_data[startup_data[:,2]<=85,0]

array([22, 28])

In [10]:
# 7. Get the data of employees who work MORE than 40 hours AND have a Performance Score >= 90.
startup_data[(startup_data[:,1]>40) & (startup_data[:,2]>=90)]

array([[40, 60, 98]])

In [13]:
# 8. The HR department decided to give a 5-point performance bonus to anyone working 50 hours or more. 
# Update the 'Performance Score' for those specific employees in the array.
startup_data[startup_data[:,1]>50,2]+=5
startup_data

array([[ 24,  45,  88],
       [ 30,  40,  92],
       [ 22,  50,  75],
       [ 35,  38,  95],
       [ 28,  42,  85],
       [ 40,  60, 108]])

In [15]:
# 9. Set a minimum baseline for hours: Replace any 'Hours Worked' less than 40 with exactly 40.
startup_data[startup_data[:,1]<40,1]=40
startup_data

array([[ 24,  45,  88],
       [ 30,  40,  92],
       [ 22,  50,  75],
       [ 35,  40,  95],
       [ 28,  42,  85],
       [ 40,  60, 108]])

In [39]:
# 10. Convert the 'Performance Score' column from a 0-100 scale to a 0.0-1.0 decimal scale.
# (e.g., 88 becomes 0.88). Update the column in-place.
startup_data = np.array([
    [24, 45, 88],   # Employee 1
    [30, 40, 92],   # Employee 2
    [22, 50, 75],   # Employee 3
    [35, 38, 95],   # Employee 4
    [28, 42, 85],   # Employee 5
    [40, 60, 98]    # Employee 6
])
startup_data=startup_data*1.0
startup_data[:,2]=startup_data[:,2]*0.01
startup_data

array([[24.  , 45.  ,  0.88],
       [30.  , 40.  ,  0.92],
       [22.  , 50.  ,  0.75],
       [35.  , 38.  ,  0.95],
       [28.  , 42.  ,  0.85],
       [40.  , 60.  ,  0.98]])